### ISSUE TITLE
Bundle with JSON output not possible anymore

### ISSUE THREAD

**Issue by khamaileon** [Cap-go/CLI#233]
npx @capgo/cli bundle zip --json

The json parameter don't work anymore on latest versions (after 4.0.12).

**Comment by riderx** [comment]
@khamaileon thanks for the report it was a regression, I just committed a fix!

**Comment by khamaileon** [comment]
@riderx Yes I thought so, thank you. By the way, you forgot a console log and it's blocking the CI.
